#!/bin/zsh

ytdl() {
  /home/userdeb/.pyenv/shims/youtube-dl \
  --config-location $HOME/.config/youtube-dl/config/youtube-dl.conf \
  -o "/mnt/c/Users/theda/Videos/uncategorized_downloads/%(upload_date)s %(title)s.%(ext)s" \
$1
}
ytdl $1 2> /mnt/c/Users/theda/Videos/uncategorized_downloads/ytt.errors.txt \

echo "The Heckin' Best, You Is."

  cd $HOME/Video/uncategorized_ytt_downloads;
  find . -type f \( -name '*.jpg' -or -name '*.webp' \) -delete \
  2> $HOME/Video/uncategorized_ytt_downloads/findfails.txt
