#!/bin/zsh

$HOME/.pyenv/shims/youtube-dl \
  --config-location $HOME/.config/youtube-dl/config/youtube-dl.conf \
  --playlist-items 1-20 \
  -o "/Volumes/fourtb/Video/channels/arts/%(uploader)s/%(upload_date)s - %(title)s.%(ext)s" > \
  /Volumes/fourtb/Video/channels/arts/yttArts.err_log.txt 2>&1 \
  --batch-file $HOME/Archive/channels/arts.txt

echo "I don't care what you say. I still think they're a good band."
