#!/bin/zsh
$HOME/.pyenv/shims/youtube-dl \
--config-location $HOME/.config/youtube-dl/config/youtube-dl.conf \
--playlist-items 1-10 \
-o "/Volumes/fourtb/Video/channels/tech/%(uploader)s/%(upload_date)s - %(title)s.%(ext)s" > \
/Volumes/fourtb/Video/channels/tech/tech_logs.txt 2>&1 \
--batch-file /Users/user/Archive/channels/tech.txt

echo "My God you've done it you brilliant bastard!"
