#!/bin/zsh
/usr/local/bin/youtube-dl \
  --config-location $HOME/.config/youtube-dl/config/youtube-dl.conf \
  --playlist-items 1-20 \
  -o "/Volumes/fourtb/Video/channels/arts/%(uploader)s/%(upload_date)s - %(title)s.%(ext)s" > \
  /Volumes/fourtb/Video/channels/arts/yttArts.err_log.txt 2>&1 \
  --batch-file $HOME/Archive/channels/arts.txt

echo "Well pull my dick and toss me off the ferris wheel! We've got a winner!"
