#!/bin/bash
$HOME/.pyenv/shims/youtube-dl \
 --config-location $HOME/.config/youtube-dl/config/youtube-dl.conf \
 --playlist-items 1-10 \
 -o "/Volumes/fourtb/Video/Channels/MMA/%(uploader)s/%(upload_date)s - %(title)s.%(ext)s" \
 --batch-file /Users/user/Archive/channels/mma.txt \

echo "Great Job Dave! Wow!"
